insert into customer(name) values ('John');
insert into customer(name) values ('JoJo');
insert into customer(name) values ('JoSuke');
insert into customer(name) values ('Johny');
insert into customer(name) values ('Joseph');
insert into customer(name) values ('Jolyn');
insert into customer(name) values ('Giorgio');
insert into customer(name) values ('Jotaroh');
insert into customer(name) values ('Josefumi');